apiVersion: apps/v1
kind: Deployment
metadata:
  name: productsapideployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - name: productscontainer
          image: pradeepsuresh/maven-e-com-web-app
          ports:
            - containerPort: 8080

          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_URL

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_USERNAME

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_PASSWORD

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: productssvc
spec:
  type: LoadBalancer
  selector:
    app: products
  ports:
    - port: 80
      targetPort: 8080