apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  DB_URL: jdbc:mysql://mysqlinstance.civomkeqohrh.us-east-1.rds.amazonaws.com:3306/pradeep_ecomm
  DB_USERNAME: admin
  DB_PASSWORD: Password#123