spring.application.name=ecommerce_backend


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://mysqlinstance.civomkeqohrh.us-east-1.rds.amazonaws.com:3306/pradeep_ecomm
spring.datasource.username=admin
spring.datasource.password=Password#123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.data.rest.base-path=/api
